normalize input -same as `goflags.NormalizedStringSliceOptions`
projectdiscovery/subfinder pull request #1072
Opened 2023-12-06 10:10 UTC by dogancanbakir

```console
$ cat domain.lst 
Google.com

$ go run . -dL domain.lst 

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/

                projectdiscovery.io

[INF] Current subfinder version v2.6.4-dev (development)
[INF] Loading provider config from /home/vscode/.config/subfinder/provider-config.yaml
[INF] Enumerating subdomains for google.com

...
googleproxy-66-249-83-183.google.com
mailit0-f43.google.com
sandbox.r2.sn-n4v7snlr.c.pack.google.com
mailqk0-f152.google.com
alt83.www.google.com
alt2871.www.google.com
googleproxy-66-249-88-182.google.com
mail-ads.r4.sn-vgqsrnld.c.pack.google.com
[INF] Found 13386 subdomains for google.com in 20 seconds 394 milliseconds
```

Closes #1071.

2024-01-08 18:55 UTC, Mzack9999 requested changes
marking as `Request Changes` to review a minor suggested change

2024-01-08 18:55 UTC, Mzack9999 commented on v2/pkg/runner/util.go
> +func normalizeLowercase(s string) string {
wouldn't this be equivalent to:
```go
return strings.ToLower(sanitize(s))
```

2024-01-11 10:29 UTC, Mzack9999 approved these changes

2024-01-11 12:30 UTC, ehsandeep approved these changes

2024-01-11 12:30 UTC, merged