Allow comments in domains file
projectdiscovery/subfinder pull request #1215
Opened 2024-04-05 19:24 UTC by RedYetiDev

This pull requests allows the domains file to have comments, prefixed with `#`. It strips everything after `#` character, and then does not process empty lines.

I.E.
```
# ProjectDiscovery
projectdiscovery.org # This is the main site
example.com # This is a demo website
```
Will be processed as
```
projectdiscovery.org
example.com
```

2024-04-05 19:26 UTC, RedYetiDev commented
If this PR is approved, I can squash if need be.

2024-04-08 09:46 UTC, GeorginaReeder commented
Thanks for your contribution @RedYetiDev , we appreciate it! :)

2024-08-05 12:28 UTC, dogancanbakir requested changes

2024-08-05 12:28 UTC, dogancanbakir commented on v2/pkg/runner/runner.go
> +		domain := normalizeLowercase(scanner.Text())
how about something like this?
```go
if stringsutil.HasSuffixAny(domain, "#", "//") {
	continue
}
```

2024-08-13 12:22 UTC, dogancanbakir commented
raised new pr https://github.com/projectdiscovery/subfinder/pull/1346

2024-08-13 12:22 UTC, closed without merging