add merklemap
projectdiscovery/subfinder pull request #1482
Opened 2024-12-19 11:42 UTC by dogancanbakir

Closess #1368

2025-01-09 13:25 UTC, ehsandeep requested changes
Getting cloudflare captcha error for every request, was it supposed to work this way?

```
./subfinder -d hackerone.com -s merklemap -v
...
...
[WRN] Encountered an error with source merklemap: unexpected status code 403 received from https://api.merklemap.com/search?stream=true&stream_progress=true&query=*.hackerone.com&page=0
[INF] Found 0 subdomains for hackerone.com in 108 milliseconds 682 microseconds
```

2025-01-10 11:21 UTC, Bundy01 commented
The first use of this source worked.
I scanned again today and found the same error as ehsandeep.

On the site, access to the API has become not free :(

2025-01-13 08:38 UTC, dogancanbakir commented
There are some updates made on the API side. Mentioning @Barre for the discussion.

2025-01-13 09:40 UTC, Barre commented
Hi,

To clarify things: Both an API token and an active subscription are now required to access these APIs.

2025-01-13 11:50 UTC, Bundy01 commented
It's a bad thing to propose API integration and then to switch this API on a pay-only basis.

2025-01-13 11:52 UTC, Barre commented
> It's a bad thing to propose API integration and then to switch this API on a pay-only basis.

I am not sure how you think it's possible to offer such services in a sustainable way, for free.

BTW, I was not aware that someone actually implemented merklemap here.

2025-01-13 17:39 UTC, ehsandeep commented
@Barre thanks for sharing update.

2025-01-13 17:39 UTC, closed without merging