Issue 378 goflag support
projectdiscovery/subfinder pull request #474
Opened 2021-12-03 17:09 UTC by LuitelSamikshya

2021-12-07 11:33 UTC, Mzack9999 requested changes
As discussed, if the config file can't be YAML unmarshaled due to deprecated structure, let's warn the user and exit. It may be possible that it's also necessary to modify https://github.com/projectdiscovery/goflags to detect the error. If that's the case, let's track it into a separate GH issue in the `goflags` repository.

2021-12-14 15:52 UTC, LuitelSamikshya commented
[https://github.com/projectdiscovery/goflags/pull/32](url)

2021-12-15 19:11 UTC, Mzack9999 approved these changes

2021-12-16 10:27 UTC, ehsandeep reviewed
@LuitelSamikshya unable to see new config file and scan is not running with this branch as well, here is example outputs:

```console
$ git branch
  dev
* issue-378-goflag-support
  master
  pr/419
  pr/424
  pr/431
  pr/433
  pr/437
  pr/438
  pr/445
  pr/461

$ go build

$ ./subfinder -d hackerone.com

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/ v2.4.9

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using subfinder, you also agree to the terms of the APIs used.

[INF] loading the default
[INF] Enumerating subdomains for hackerone.com
[INF] Found 0 subdomains for hackerone.com in 144 microseconds

$ ls ~/.config/subfinder/
config.yaml
```

2021-12-27 07:03 UTC, Mzack9999 requested changes
It seems like there is some issue related to the integration - moving back to `in progress`:
```console
$ go run . -d hackerone.com

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/ v2.4.9

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using subfinder, you also agree to the terms of the APIs used.

[INF] loading the default
[INF] Enumerating subdomains for hackerone.com
[INF] Found 0 subdomains for hackerone.com in 258 microseconds
$ go build .
$ ./subfinder . -d hackerone.com

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/ v2.4.9

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using subfinder, you also agree to the terms of the APIs used.

[INF] loading the default
[FTL] Program exiting: no input list provided
$ ls ~/.config/subfinder/
config.json     config.yaml
```

2022-01-11 13:27 UTC, ehsandeep submitted a review, later dismissed
Here are a few things that we need to consider for automatic migration of the existing provider keys/credentials to the new provider config file.

- Move existing **keys/token** of providers to the newly created provider config file at `$HOME/.config/subfinder/provider.yaml`
- New flag to use custom source/provider config file, as default `$HOME/.config/subfinder/provider.yaml` will be created and used.
- We can safely remove following controls from the current config file as we already this information in the code `resolvers`,`sources`, `all-sources`,`recursive`
- Create default `goflags` config for the subfinder at `$HOME/.config/subfinder/config.yaml`

2022-01-27 05:09 UTC, LuitelSamikshya commented
[https://github.com/projectdiscovery/goflags/pull/32](url)

2022-01-27 11:25 UTC, Mzack9999 requested changes
It's necessary to update `go.mod` to use the latest commit of https://github.com/projectdiscovery/goflags/pull/32

2022-01-27 11:25 UTC, Mzack9999 commented on v2/pkg/runner/options.go
> +			options.ConfigFile = path.Join(config, "provider.yaml")
please use `filepath.Join`

2022-01-27 11:25 UTC, Mzack9999 commented on v2/pkg/runner/options.go
> +			options.ConfigFile = path.Join(config, "config.yaml")
please use `filepath.Join`

2022-01-28 05:07 UTC, LuitelSamikshya commented on v2/pkg/runner/options.go
> +			options.ConfigFile = path.Join(config, "provider.yaml")
Done

2022-01-28 05:07 UTC, LuitelSamikshya commented on v2/pkg/runner/options.go
> +			options.ConfigFile = path.Join(config, "config.yaml")
done

2022-02-02 09:17 UTC, Mzack9999 requested changes
Providers are correctly migrated to `$HOME/.config/subfinder/provider.yaml`, anyway invoking again the tool trigger an EOF error for `$HOME/.config/subfinder/config.yaml`. If no options are specified, the tool should load the default config from `config.yaml` and the providers from the default `provider.yaml`.

2022-02-04 07:45 UTC, Mzack9999 requested changes
If the `$home/.config/subfinder` folder is empty I guess the application should re-generate empty configuration files:
```console
$ rm -rf /Users/user/.config/subfinder/
$ echo hackerone.com | ./subfinder 

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/ v2.4.9

                projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using subfinder, you also agree to the terms of the APIs used.

[INF] loading the default
[FTL] Could not read configuration file /Users/user/.config/subfinder/provider.yaml: open /Users/user/.config/subfinder/provider.yaml: no such file or directory
```

2022-02-07 16:45 UTC, LuitelSamikshya commented
<img width="639" alt="Screen Shot 2022-02-07 at 10 42 02 AM" src="https://user-images.githubusercontent.com/85764322/152832382-149604cd-f371-48c3-92b7-6331789343ee.png">

2022-02-21 14:32 UTC, closed without merging