new source dnsrepo
projectdiscovery/subfinder pull request #501
Opened 2022-02-16 15:25 UTC by LuitelSamikshya

This PR adds support for  new source https://dnsrepo.noc.org/

2022-02-21 14:10 UTC, its0x08 approved these changes

2022-02-21 16:09 UTC, ehsandeep reviewed
API needs to be supported in this case, waiting for further information as commented here https://github.com/projectdiscovery/subfinder/issues/475#issuecomment-1047025710

2022-09-08 07:47 UTC, ehsandeep requested changes
@LuitelSamikshya Instead of scrapping, we can utilize the API endpoint to pull all the results, including the integration test.

API Endpoint:

```
https://dnsrepo.noc.org/api/?apikey=API_KEY&search=hackerone.com
```

API Details: https://dnsrepo.noc.org/?apiaccess

2022-09-16 18:48 UTC, ehsandeep approved these changes
```console
./subfinder -s dnsrepo -d hackerone.com

               __    _____           __         
   _______  __/ /_  / __(_)___  ____/ /__  _____
  / ___/ / / / __ \/ /_/ / __ \/ __  / _ \/ ___/
 (__  ) /_/ / /_/ / __/ / / / / /_/ /  __/ /    
/____/\__,_/_.___/_/ /_/_/ /_/\__,_/\___/_/ v2.5.3

		projectdiscovery.io

Use with caution. You are responsible for your actions
Developers assume no liability and are not responsible for any misuse or damage.
By using subfinder, you also agree to the terms of the APIs used.

[INF] Loading provider config from '/Users/geekboy/.config/subfinder/provider-config.yaml'
[INF] Enumerating subdomains for 'hackerone.com'
docs.hackerone.com
api.hackerone.com
b.ns.hackerone.com
gslink.hackerone.com
gsemail.hackerone.com
mta-sts.managed.hackerone.com
www.hackerone.com
support.hackerone.com
zendesk3.hackerone.com
a.ns.hackerone.com
mta-sts.hackerone.com
zendesk2.hackerone.com
[INF] Found 12 subdomains for 'hackerone.com' in 1 second 297 milliseconds
```

2022-09-20 16:04 UTC, Ice3man543 approved these changes

2022-09-20 17:23 UTC, merged