Prevent EnumerateSubdomains() from continuing if there is an error in Regex
projectdiscovery/subfinder pull request #672
Opened 2022-10-17 18:48 UTC by r0nk

2022-10-17 18:49 UTC, r0nk commented
Should fix https://github.com/projectdiscovery/subfinder/issues/671#issue-1412049848

2022-10-17 21:08 UTC, Mzack9999 requested changes

2022-10-17 21:08 UTC, Mzack9999 commented on v2/pkg/passive/passive.go
> +			close(results)
I guess we can put a `defer close(results)` at the beginning of the go routine

2022-10-17 21:08 UTC, Mzack9999 commented on v2/pkg/passive/passive.go
>  		close(results)
redundant if previous suggestion is implemented

2022-10-17 21:24 UTC, Mzack9999 approved these changes

2022-10-19 19:42 UTC, Ice3man543 approved these changes

2022-10-19 21:44 UTC, merged