resolve failing cases
projectdiscovery/subfinder pull request #720
Opened 2022-11-25 13:28 UTC by ShubhamRasal

2022-11-28 07:00 UTC, ShubhamRasal commented
crtsh and commoncrawl errors are very random. 
most of the time tests fails due to 503, and connection timeout error of sources.

2022-11-28 10:18 UTC, Mzack9999 requested changes
lgtm - not related but I'd like to propose removing `push` from github actions:
```
on:
  push:
  pull_request:
```
The interested actions are:
- [x] build-test.yml
- [ ] lint-test.yml

2022-11-29 12:45 UTC, Mzack9999 approved these changes
lgtm - faulty sources removal tracked at https://github.com/projectdiscovery/subfinder/issues/722

2022-11-29 12:49 UTC, ehsandeep approved these changes

2022-11-29 12:49 UTC, merged

2022-11-29 17:28 UTC, vzamanillo commented on v2/pkg/subscraping/agent.go
> +		}).Dial,
The timeout is set when the http.client is initialized, this is a dup.