Add ctx param in agent enumerate method
projectdiscovery/subfinder pull request #756
Opened 2023-02-09 15:51 UTC by EndPositive

so that I can cancel the enumeration manually too

2023-02-15 19:59 UTC, tarunKoyalwar commented
@EndPositive , How about implementing the same without making any breaking changes to API since many users import subfinder as library . 

Ex:

```go
func (a *Agent) EnumerateSubdomains(domain string, proxy string, rateLimit, timeout int, maxEnumTime time.Duration) chan subscraping.Result {
return a.EnumerateSubdomainsWithCtx(context.Background(),domain , proxy , rateLimit, timeout , maxEnumTime)
}
```

```go
func (a *Agent) EnumerateSubdomainsWithCtx(ctx context.Context, domain string, proxy string, rateLimit, timeout int, maxEnumTime time.Duration) chan subscraping.Result 
```

2023-02-15 20:00 UTC, tarunKoyalwar requested changes

2023-02-15 20:00 UTC, tarunKoyalwar commented on v2/pkg/passive/passive.go
>  		defer close(results)
@EndPositive , How about implementing the same without making any breaking changes to API since many users import subfinder as library .

2023-02-16 09:30 UTC, tarunKoyalwar approved these changes
lgtm!

2023-02-16 11:22 UTC, tarunKoyalwar commented
@ehsandeep , build test is currently failing due to a #761 . It is WIP and for this PR we can either merge it to `dev` or rebase after #761  is resolved

2023-02-17 22:23 UTC, ehsandeep approved these changes

2023-02-17 22:23 UTC, merged