Extract subdomains in case of 404
projectdiscovery/subfinder pull request #845
Opened 2023-05-24 11:06 UTC by dogancanbakir

Closes #774

2023-05-24 14:14 UTC, Mzack9999 requested changes
The issue was potentially extracting from the bottom of the page the 100 suggested names related to the certificate, shown even in case of a 404 error page.

![image](https://github.com/projectdiscovery/subfinder/assets/13421144/4ede8a6d-ca7f-498e-b1dd-12d4ad633a20)

2023-05-25 08:37 UTC, dogancanbakir commented
The cause of the build failure is the source riddler returning a 403 error. It can be temporary so I believe we can ignore it for now.
<img width="1300" alt="image" src="https://github.com/projectdiscovery/subfinder/assets/65292895/53fea9f8-d6ae-419c-ad71-d4d51767cd48">

2023-05-25 09:16 UTC, Mzack9999 approved these changes
lgtm
```console
$ ./subfinder -d allegion.com -s digitorus           
...
NF] Enumerating subdomains for allegion.com
notifications-uat.allegion.com
smetrics.allegion.com
startsmart.allegion.com
m3uid01.allegion.com
americas.allegion.com
www.allegion.com
```

2023-05-25 09:22 UTC, ehsandeep approved these changes

2023-05-25 09:22 UTC, merged