add builtwith as a source
projectdiscovery/subfinder pull request #960
Opened 2023-08-23 13:43 UTC by dogancanbakir

Closes #959

2023-08-23 22:06 UTC, Mzack9999 requested changes
Could you provide an example query, I was able to get an api key, but unfortunately it's unclear which is the expected format:
```console
$ go run . -d google -s builtwith -v
...
[INF] Found 0 subdomains for google.com in 459 milliseconds 533 microseconds
$ go run . -d google.com -s builtwith -v
...
[INF] Found 0 subdomains for google in 420 milliseconds 752 microseconds
...
```

I think it's also worth updating the docs

2023-08-23 22:06 UTC, Mzack9999 commented on v2/pkg/subscraping/sources/builtwith/builtwith.go
> +		// x, _ := io.ReadAll(resp.Body)
unused debug instructions

2023-08-24 06:59 UTC, dogancanbakir commented
@Mzack9999 I have updated the initial message with an example and have also made changes to the document.

2023-08-24 12:26 UTC, Mzack9999 approved these changes
lgtm - Apparently `google.com` had really zero results xD

2023-09-12 09:04 UTC, merged